lessons/week-09/downloads/challenge/config/routes.rb
Challenge::Application.routes.draw do
  resources :posts
  resources :moderate, only: [:index, :create]

  root 'welcome#index'

end

lessons/week-09/downloads/challenge/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :body, presence: true
end

lessons/week-09/downloads/challenge/app/controllers/moderate_controller.rb
class ModerateController < ApplicationController
end

lessons/week-09/downloads/challenge/app/helpers/moderate_helper.rb
module ModerateHelper
end

lessons/week-09/downloads/challenge/app/views/posts/_form.html.erb
<%= form_for @post, html: {name: 'posts', novalidate: true, 'ng-submit' => 'submitForm($event)'} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, name: 'title', required: true, 'ng-model' => 'post.title' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, name: 'body', required: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lessons/week-09/downloads/challenge/app/views/welcome/index.html.erb
<h1>Challenge</h1>
<p>Validate a form using AngularJS, choosing either the <%= link_to 'moderate', moderate_index_path %> or <%= link_to 'difficult', posts_path %> implementation.</p>

<ul>
  <li>Set up this app to use AngularJS</li>
  <li>Create a style for invalid inputs</li>
  <li>Validate the form, showing when the field is invalid.</li>
  <li>BONUS: Only show the invalid style after the form is submitted.</li>
</ul>